### YamlMime:PythonClass
uid: azure.eventhub.exceptions.ConnectError
name: ConnectError
fullName: azure.eventhub.exceptions.ConnectError
module: azure.eventhub.exceptions
inheritances:
- azure.eventhub.exceptions.EventHubError
summary: Failed to connect to the Event Hubs service.
constructor:
  syntax: 'ConnectError(message: str, details: List[str] | None = None)'
  parameters:
  - name: message
    isRequired: true
  - name: details
    defaultValue: None
methods:
- uid: azure.eventhub.exceptions.ConnectError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.eventhub.exceptions.ConnectError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.eventhub.exceptions.ConnectError.args
  name: args
