### YamlMime:PythonClass
uid: azure.durable_functions.entity.InternalEntityException
name: InternalEntityException
fullName: azure.durable_functions.entity.InternalEntityException
module: azure.durable_functions.entity
inheritances:
- builtins.Exception
summary: Framework-internal Exception class (for internal use only).
constructor:
  syntax: InternalEntityException()
methods:
- uid: azure.durable_functions.entity.InternalEntityException.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.durable_functions.entity.InternalEntityException.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.durable_functions.entity.InternalEntityException.args
  name: args
