### YamlMime:PythonClass
uid: azure.iot.device.iot_exceptions.IoTHubError
name: IoTHubError
fullName: azure.iot.device.iot_exceptions.IoTHubError
module: azure.iot.device.iot_exceptions
inheritances:
- builtins.Exception
summary: Represents a failure reported by IoT Hub
constructor:
  syntax: IoTHubError()
methods:
- uid: azure.iot.device.iot_exceptions.IoTHubError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.iot.device.iot_exceptions.IoTHubError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.iot.device.iot_exceptions.IoTHubError.args
  name: args
