### YamlMime:PythonClass
uid: azure.ai.ml.exceptions.InvalidLocalEndpointError
name: InvalidLocalEndpointError
fullName: azure.ai.ml.exceptions.InvalidLocalEndpointError
module: azure.ai.ml.exceptions
inheritances:
- azure.ai.ml.exceptions.MlException
summary: Exception raised when local endpoint is invalid.
constructor:
  syntax: 'InvalidLocalEndpointError(message: str, no_personal_data_message: str,
    error_category=''UserError'')'
  parameters:
  - name: message
  - name: no_personal_data_message
  - name: error_category
    defaultValue: UserError
