### YamlMime:PythonClass
uid: azure.cognitiveservices.language.luis.runtime.models.ErrorException
name: ErrorException
fullName: azure.cognitiveservices.language.luis.runtime.models.ErrorException
module: azure.cognitiveservices.language.luis.runtime.models
inheritances:
- msrest.exceptions.HttpOperationError
summary: 'Server responsed with exception of type: ''Error''.'
constructor:
  syntax: ErrorException(deserialize, response, *args)
  parameters:
  - name: deserialize
    description: A deserializer
    isRequired: true
  - name: response
    description: Server response to be deserialized.
    isRequired: true
methods:
- uid: azure.cognitiveservices.language.luis.runtime.models.ErrorException.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.cognitiveservices.language.luis.runtime.models.ErrorException.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.cognitiveservices.language.luis.runtime.models.ErrorException.args
  name: args
