### YamlMime:PythonClass
uid: azure.mgmt.cosmosdb.models.ConnectionError
name: ConnectionError
fullName: azure.mgmt.cosmosdb.models.ConnectionError
module: azure.mgmt.cosmosdb.models
inheritances:
- msrest.serialization.Model
summary: ConnectionError.
constructor:
  syntax: 'ConnectionError(*, connection_state: Optional[Union[str, _models.ConnectionState]]
    = None, i_p_from: Optional[str] = None, i_p_to: Optional[str] = None, port: Optional[int]
    = None, exception: Optional[str] = None, **kwargs)'
variables:
- description: 'The kind of connection error that occurred. Known values are:

    "Unknown", "OK", "OperatorToDataCenterNetworkError", "DatacenterToDatacenterNetworkError",

    "InternalOperatorToDataCenterCertificateError", "InternalError".'
  name: connection_state
  types:
  - <xref:str>
  - <xref:azure.mgmt.cosmosdb.models.ConnectionState>
- description: The IP of host that originated the failed connection.
  name: i_p_from
  types:
  - <xref:str>
- description: The IP that the connection attempted to reach.
  name: i_p_to
  types:
  - <xref:str>
- description: The TCP port the connection was attempted on.
  name: port
  types:
  - <xref:int>
- description: Detailed error message about the failed connection.
  name: exception
  types:
  - <xref:str>
