### YamlMime:PythonClass
uid: azure.core.polling.base_polling.BadResponse
name: BadResponse
fullName: azure.core.polling.base_polling.BadResponse
module: azure.core.polling.base_polling
inheritances:
- builtins.Exception
constructor:
  syntax: BadResponse()
methods:
- uid: azure.core.polling.base_polling.BadResponse.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.core.polling.base_polling.BadResponse.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.core.polling.base_polling.BadResponse.args
  name: args
